version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    depends_on:
      - es02
      - es03

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.1
    networks:
      elastic:
    depends_on:
      - es01

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.1
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      elastic:
    depends_on:
      - es01
    ports:
    - 5601:5601

  metricbeat_system:
    image: docker.elastic.co/beats/metricbeat-oss:7.8.1
    build:
      dockerfile: Dockerfile
      context: .
#    command: ["setup", "-E", "setup.kibana.host=elk:5601", "-E", "output.elasticsearch.hosts=[\"elk:9200\"]", "-e", "-d", "*"]
#    command: ["-E", "output.elasticsearch.hosts=[\"elk:9200\"]", "-e", "-d", "*"]  # Enable all debug logging
    command: ["-E", "output.elasticsearch.hosts=[\"es01:9200\"]", "-e", "-d", "publish"]  # Enable publish debug logging
#    command: ["-E", "output.elasticsearch.hosts=[\"elk:9200\"]", "-e"]
    networks:
      elastic:
    depends_on:
      - es01
    user: root
    cap_add:
      - CAP_SYS_PTRACE
      - CAP_DAC_READ_SEARCH
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    - /proc:/hostfs/proc:ro
    - /:/hostfs:ro

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
